"use client"
import { motion } from "framer-motion"

export default function ScoreCard({ data, idea }) {
  const score = data.overall_score || 0
  const scoreColor = score >= 70 ? "#00ff64" : score >= 50 ? "#ff9600" : "#ff3264"
  const scoreShadow = score >= 70 ? "0 0 30px rgba(0,255,100,0.5)" : score >= 50 ? "0 0 30px rgba(255,150,0,0.5)" : "0 0 30px rgba(255,50,100,0.5)"
  const breakdown = data.score_breakdown || {}

  const handleExport = () => {
    const content = `STARTUPIQ AI - OPPORTUNITY SCORE CARD\n======================================\nIdea: ${idea}\nOverall Score: ${score}/100\nIndia Market Readiness: ${data.india_market_readiness?.toUpperCase()}\n\nSCORE BREAKDOWN:\n- Market Demand: ${breakdown.demand}/25\n- Competition: ${breakdown.competition}/25\n- Market Timing: ${breakdown.timing}/25\n- Feasibility: ${breakdown.feasibility}/25\n\nTOP 3 STRENGTHS:\n${(data.top_3_strengths || []).map((s, i) => `${i + 1}. ${s}`).join("\n")}\n\nTOP 3 RISKS:\n${(data.top_3_risks || []).map((r, i) => `${i + 1}. ${r}`).join("\n")}\n\nRECOMMENDED NEXT ACTION:\n${data.recommended_next_action}\n\n======================================\nSource: Web Intelligence + AI Synthesis\nGenerated by StartupIQ AI - SummerSaaS 2026`.trim()
    const blob = new Blob([content], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = "startupiq-scorecard.txt"
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-bold text-white">🏆 Opportunity Score Card</h2>
        <button onClick={handleExport}
          className="text-sm px-4 py-2 rounded-xl transition-all flex items-center gap-2 btn-neon-blue">
          📄 Export Report
        </button>
      </div>

      {/* Main Score */}
      <motion.div initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }}
        className="card text-center py-10"
        style={{borderColor: `${scoreColor}40`, boxShadow: `${scoreShadow}, inset 0 0 40px rgba(0,0,0,0.4)`}}>
        <motion.div initial={{ scale: 0 }} animate={{ scale: 1 }} transition={{ delay: 0.2, type: "spring", stiffness: 200 }}
          className="inline-flex items-center justify-center w-40 h-40 rounded-full mb-4"
          style={{ border: `4px solid ${scoreColor}`, boxShadow: `${scoreShadow}, inset 0 0 20px rgba(0,0,0,0.5)` }}>
          <div>
            <div className="text-5xl font-black" style={{ color: scoreColor, textShadow: scoreShadow }}>{score}</div>
            <div className="text-sm" style={{color: "rgba(150,150,200,0.6)"}}>/100</div>
          </div>
        </motion.div>
        <div className="mt-2">
          <span className="text-sm px-4 py-2 rounded-full font-semibold badge-neon"
            style={{ background: `${scoreColor}15`, border: `1px solid ${scoreColor}50`, color: scoreColor }}>
            {data.india_market_readiness?.toUpperCase()} FOR INDIA
          </span>
        </div>
      </motion.div>

      {/* Score Breakdown */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="card">
        <h3 className="text-sm mb-4" style={{color: "rgba(150,150,200,0.7)"}}>Score Breakdown</h3>
        <div className="space-y-3">
          {[
            { label: "Market Demand", value: breakdown.demand, max: 25, color: "#00d4ff" },
            { label: "Competition Level", value: breakdown.competition, max: 25, color: "#bf00ff" },
            { label: "Market Timing", value: breakdown.timing, max: 25, color: "#00ff64" },
            { label: "Feasibility", value: breakdown.feasibility, max: 25, color: "#ff9600" }
          ].map((item, i) => (
            <div key={i}>
              <div className="flex justify-between text-sm mb-1">
                <span style={{color: "rgba(150,150,200,0.8)"}}>{item.label}</span>
                <span className="font-semibold text-white">{item.value}/{item.max}</span>
              </div>
              <div className="h-2 rounded-full overflow-hidden" style={{background: "rgba(100,100,255,0.1)"}}>
                <motion.div initial={{ width: 0 }} animate={{ width: `${(item.value / item.max) * 100}%` }}
                  transition={{ delay: 0.4 + i * 0.1, duration: 0.6 }}
                  className="h-full rounded-full"
                  style={{ background: item.color, boxShadow: `0 0 8px ${item.color}` }} />
              </div>
            </div>
          ))}
        </div>
      </motion.div>

      {/* Strengths and Risks */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.4 }}
          className="card" style={{borderColor: "rgba(0,255,100,0.3)", boxShadow: "0 0 15px rgba(0,255,80,0.06)"}}>
          <h3 className="font-semibold mb-3 text-sm text-neon-green">💪 Top 3 Strengths</h3>
          <div className="space-y-2">
            {(data.top_3_strengths || []).map((s, i) => (
              <div key={i} className="flex items-start gap-2 p-3 rounded-xl"
                style={{background: "rgba(0,100,30,0.15)", border: "1px solid rgba(0,255,100,0.15)"}}>
                <span className="text-neon-green text-sm">✓</span>
                <p className="text-gray-300 text-sm">{s}</p>
              </div>
            ))}
          </div>
        </motion.div>
        <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.4 }}
          className="card" style={{borderColor: "rgba(255,50,100,0.3)", boxShadow: "0 0 15px rgba(255,0,80,0.06)"}}>
          <h3 className="font-semibold mb-3 text-sm text-neon-red">⚠️ Top 3 Risks</h3>
          <div className="space-y-2">
            {(data.top_3_risks || []).map((r, i) => (
              <div key={i} className="flex items-start gap-2 p-3 rounded-xl"
                style={{background: "rgba(100,0,20,0.15)", border: "1px solid rgba(255,50,100,0.15)"}}>
                <span className="text-neon-red text-sm">✗</span>
                <p className="text-gray-300 text-sm">{r}</p>
              </div>
            ))}
          </div>
        </motion.div>
      </div>

      {/* Next Action */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.5 }}
        className="card" style={{borderColor: "rgba(0,150,255,0.3)", background: "rgba(0,50,100,0.15)", boxShadow: "0 0 20px rgba(0,100,255,0.08)"}}>
        <h3 className="font-semibold mb-2 text-sm text-neon-blue">🚀 Recommended Next Action</h3>
        <p className="text-gray-200 text-sm leading-relaxed">{data.recommended_next_action}</p>
      </motion.div>

      {/* Buttons */}
      <div className="flex gap-3">
        <button onClick={handleExport} className="flex-1 py-3 rounded-xl text-sm font-semibold transition-all btn-neon-blue">
          📄 Export Score Card
        </button>
        <button onClick={() => window.location.href = "/"} className="flex-1 py-3 rounded-xl text-sm font-semibold transition-all"
          style={{background: "rgba(30,30,60,0.5)", border: "1px solid rgba(100,100,255,0.2)", color: "#8888cc"}}>
          🔍 Analyze Another Idea
        </button>
      </div>
    </div>
  )
}