"use client"
import { motion } from "framer-motion"

export default function ScoreCard({ data, idea }) {
  const score = data.overall_score || 0
  const scoreColor = score >= 70 ? "#22c55e" : score >= 50 ? "#eab308" : "#ef4444"
  const scoreBg = score >= 70 ? "from-green-900/30 to-green-800/10" : score >= 50 ? "from-yellow-900/30 to-yellow-800/10" : "from-red-900/30 to-red-800/10"

  const breakdown = data.score_breakdown || {}

  const handleExport = () => {
    const content = `
STARTUPIQ AI - OPPORTUNITY SCORE CARD
======================================
Idea: ${idea}
Overall Score: ${score}/100
India Market Readiness: ${data.india_market_readiness?.toUpperCase()}

SCORE BREAKDOWN:
- Market Demand: ${breakdown.demand}/25
- Competition: ${breakdown.competition}/25
- Market Timing: ${breakdown.timing}/25
- Feasibility: ${breakdown.feasibility}/25

TOP 3 STRENGTHS:
${(data.top_3_strengths || []).map((s, i) => `${i + 1}. ${s}`).join("\n")}

TOP 3 RISKS:
${(data.top_3_risks || []).map((r, i) => `${i + 1}. ${r}`).join("\n")}

RECOMMENDED NEXT ACTION:
${data.recommended_next_action}

======================================
Source: Web Intelligence + AI Synthesis
All insights are advisory recommendations only.
Generated by StartupIQ AI - SummerSaaS 2026
    `.trim()

    const blob = new Blob([content], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = "startupiq-scorecard.txt"
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-bold text-white">🏆 Opportunity Score Card</h2>
        <button
          onClick={handleExport}
          className="bg-blue-600 hover:bg-blue-700 text-white text-sm px-4 py-2 rounded-xl transition-all flex items-center gap-2"
        >
          📄 Export Report
        </button>
      </div>

      {/* Main Score */}
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        className={`card bg-gradient-to-br ${scoreBg} text-center py-10`}
      >
        <motion.div
          initial={{ scale: 0 }}
          animate={{ scale: 1 }}
          transition={{ delay: 0.2, type: "spring", stiffness: 200 }}
          className="inline-flex items-center justify-center w-40 h-40 rounded-full border-4 mb-4"
          style={{ borderColor: scoreColor }}
        >
          <div>
            <div className="text-5xl font-bold" style={{ color: scoreColor }}>{score}</div>
            <div className="text-gray-500 text-sm">/100</div>
          </div>
        </motion.div>
        <div className="mt-2">
          <span className="text-sm px-4 py-2 rounded-full font-semibold" style={{ background: `${scoreColor}20`, color: scoreColor }}>
            {data.india_market_readiness?.toUpperCase()} FOR INDIA
          </span>
        </div>
      </motion.div>

      {/* Score Breakdown */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="card">
        <h3 className="text-gray-400 text-sm mb-4">Score Breakdown</h3>
        <div className="space-y-3">
          {[
            { label: "Market Demand", value: breakdown.demand, max: 25, color: "#3B82F6" },
            { label: "Competition Level", value: breakdown.competition, max: 25, color: "#8B5CF6" },
            { label: "Market Timing", value: breakdown.timing, max: 25, color: "#10B981" },
            { label: "Feasibility", value: breakdown.feasibility, max: 25, color: "#F59E0B" }
          ].map((item, i) => (
            <div key={i}>
              <div className="flex justify-between text-sm mb-1">
                <span className="text-gray-400">{item.label}</span>
                <span className="text-white font-semibold">{item.value}/{item.max}</span>
              </div>
              <div className="h-2 bg-gray-800 rounded-full overflow-hidden">
                <motion.div
                  initial={{ width: 0 }}
                  animate={{ width: `${(item.value / item.max) * 100}%` }}
                  transition={{ delay: 0.4 + i * 0.1, duration: 0.6 }}
                  className="h-full rounded-full"
                  style={{ background: item.color }}
                />
              </div>
            </div>
          ))}
        </div>
      </motion.div>

      {/* Strengths and Risks */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.4 }} className="card">
          <h3 className="text-green-400 font-semibold mb-3 text-sm">💪 Top 3 Strengths</h3>
          <div className="space-y-2">
            {(data.top_3_strengths || []).map((s, i) => (
              <div key={i} className="strength-card flex items-start gap-2">
                <span className="text-green-400 text-sm">✓</span>
                <p className="text-gray-300 text-sm">{s}</p>
              </div>
            ))}
          </div>
        </motion.div>

        <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.4 }} className="card">
          <h3 className="text-red-400 font-semibold mb-3 text-sm">⚠️ Top 3 Risks</h3>
          <div className="space-y-2">
            {(data.top_3_risks || []).map((r, i) => (
              <div key={i} className="risk-card flex items-start gap-2">
                <span className="text-red-400 text-sm">✗</span>
                <p className="text-gray-300 text-sm">{r}</p>
              </div>
            ))}
          </div>
        </motion.div>
      </div>

      {/* Next Action */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.5 }} className="card border-blue-800/50 bg-blue-900/10">
        <h3 className="text-blue-400 font-semibold mb-2 text-sm">🚀 Recommended Next Action</h3>
        <p className="text-white text-sm leading-relaxed">{data.recommended_next_action}</p>
      </motion.div>

      {/* Action Buttons */}
      <div className="flex gap-3">
        <button onClick={handleExport} className="flex-1 bg-blue-600 hover:bg-blue-700 text-white py-3 rounded-xl text-sm font-semibold transition-all">
          📄 Export Score Card
        </button>
        <button onClick={() => window.location.href = "/"} className="flex-1 bg-gray-800 hover:bg-gray-700 text-white py-3 rounded-xl text-sm font-semibold transition-all">
          🔍 Analyze Another Idea
        </button>
      </div>
    </div>
  )
}